/**
 * Aktuelles – Typen & Feed-Loader.
 * Lädt zur Laufzeit `public/data/aktuelles_feeds.json`; Fallback ist der
 * gebündelte Build-Import. Wird vom monatlichen Workflow aktualisiert.
 */
import fallback from './aktuelles_feeds.json';

export interface Person { name: string; role: string; }

export interface NewsGalleryItem {
  url: string;
  title?: string;
  caption?: string;
}

export interface NewsItem {
  id: string;
  category: string;
  date: string;
  title: string;
  image: string;
  gallery?: NewsGalleryItem[];
  location?: string;
  shortText: string;
  highlights: string[];
  speech: string;
  persons: Person[];
  isAutoGenerated?: boolean;
  sourceEventId?: string;
}

export interface EventItem {
  id: string;
  title: string;
  date: string;
  location: string;
  category: string;
  image: string;
  description: string;
  link: string;
}

export interface BlogItem {
  id: string;
  title: string;
  date: string;
  author: string;
  category: string;
  image: string;
  excerpt: string;
  link: string;
}

export interface AktuellesFeeds {
  generatedAt: string;
  lastUpdated: { news: string; events: string; blogs: string };
  news: NewsItem[];
  events: EventItem[];
  blogs: BlogItem[];
}

export interface CountdownInfo {
  status: 'past' | 'today' | 'tomorrow' | 'upcoming';
  days: number;
  label: string;
}

/**
 * Berechnet den "noch X Tage"-Countdown für ein Veranstaltungsdatum.
 */
export function getEventCountdown(isoDate?: string): CountdownInfo | null {
  if (!isoDate) return null;
  try {
    const target = new Date(isoDate);
    if (isNaN(target.getTime())) return null;

    const now = new Date();
    // Rechnen auf Tagesbasis (Mitternacht)
    const targetDay = new Date(target.getFullYear(), target.getMonth(), target.getDate()).getTime();
    const todayDay = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
    const diffDays = Math.round((targetDay - todayDay) / (1000 * 60 * 60 * 24));

    if (diffDays < 0) {
      return { status: 'past', days: diffDays, label: 'Rückblick' };
    }
    if (diffDays === 0) {
      return { status: 'today', days: 0, label: 'Heute!' };
    }
    if (diffDays === 1) {
      return { status: 'tomorrow', days: 1, label: 'Morgen!' };
    }
    return { status: 'upcoming', days: diffDays, label: `noch ${diffDays} Tage` };
  } catch {
    return null;
  }
}

/**
 * Erzeugt automatisch nach jedem vergangenen Event einen Rückblick-Eintrag
 * in den Aktuelles-News, falls noch kein manueller Eintrag existiert.
 */
export function deriveAutoNewsFromEvents(events: EventItem[] = [], existingNews: NewsItem[] = []): NewsItem[] {
  const now = Date.now();
  const existingIds = new Set(existingNews.map((n) => n.id));
  const existingSourceIds = new Set(
    existingNews.map((n) => n.sourceEventId).filter(Boolean)
  );

  const autoRecaps: NewsItem[] = [];

  for (const ev of events) {
    try {
      const evTime = new Date(ev.date).getTime();
      // Nur vergangene Events
      if (!isNaN(evTime) && evTime <= now) {
        const recapId = `recap-event-${ev.id}`;
        if (!existingIds.has(recapId) && !existingSourceIds.has(ev.id)) {
          const formattedEventDate = new Date(ev.date).toLocaleDateString('de-DE', {
            day: '2-digit',
            month: 'long',
            year: 'numeric',
          });
          const city = ev.location ? ev.location.split(',')[0].trim() : 'Mittelhessen';

          autoRecaps.push({
            id: recapId,
            category: 'Rückblick',
            date: ev.date,
            title: `Rückblick: ${ev.title}`,
            image: ev.image,
            location: ev.location,
            shortText: `Erfolgreicher Rückblick auf unser Event „${ev.title}“ am ${formattedEventDate}: Zahlreiche Teilnehmende kamen in ${city} zusammen, um Gemeinschaft und lebendigen Dialog zu erleben.`,
            highlights: [
              `Veranstaltung: ${ev.title}`,
              `Datum: ${formattedEventDate}`,
              `Ort: ${ev.location}`,
              `Bereich: ${ev.category}`,
              ev.description ? `${ev.description.slice(0, 150)}...` : 'Gemeinsames Engagement für Bildung und Verständigung in Mittelhessen.'
            ],
            speech: '„Herzlichen Dank an alle Teilnehmenden, Gäste und ehrenamtlichen Helferinnen und Helfer, die dieses Treffen mit Leben gefüllt haben!“',
            persons: [],
            isAutoGenerated: true,
            sourceEventId: ev.id,
          });
        }
      }
    } catch {
      // Ignoriere fehlerhafte Datumsangaben
    }
  }

  // Zusammenführen und nach Datum absteigend sortieren
  const combined = [...existingNews, ...autoRecaps];
  combined.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  return combined;
}

function normalizeAssetUrl(url?: string): string {
  if (!url) return '';
  if (url.startsWith('http://') || url.startsWith('https://') || url.startsWith('data:') || url.startsWith('//')) {
    return url;
  }
  const base = import.meta.env.BASE_URL || '/';
  const prefix = base.endsWith('/') ? base.slice(0, -1) : base;
  const path = url.startsWith('/') ? url : `/${url}`;
  return `${prefix}${path}`;
}

function processFeeds(raw: AktuellesFeeds): AktuellesFeeds {
  if (!raw) return raw;
  // News wird separat geführt und enthält nur echte Vereinsnachrichten (keine Duplikate aus Events)
  const rawNews = Array.isArray(raw.news) ? raw.news : [];
  const normalizedNews = rawNews.map((n) => ({
    ...n,
    image: normalizeAssetUrl(n.image),
    gallery: n.gallery?.map((g) => ({
      ...g,
      url: normalizeAssetUrl(g.url),
    })),
  }));
  return {
    ...raw,
    news: normalizedNews,
  };
}

export const AKTUELLES_FALLBACK = processFeeds(fallback as unknown as AktuellesFeeds);
export const AKTUELLES_URL = `${import.meta.env.BASE_URL}data/aktuelles_feeds.json`;

export function formatDate(iso?: string) {
  if (!iso) return '–';
  try {
    return new Date(iso).toLocaleDateString('de-DE', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
    });
  } catch {
    return '–';
  }
}

import { useEffect, useState } from 'react';

/** Lädt die Feeds zur Laufzeit, mit gebündeltem Fallback und Auto-News aus Events. */
export function useAktuelles(): AktuellesFeeds {
  const [feeds, setFeeds] = useState<AktuellesFeeds>(AKTUELLES_FALLBACK);
  useEffect(() => {
    let active = true;
    fetch(AKTUELLES_URL, { cache: 'no-cache' })
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((d: AktuellesFeeds) => {
        if (active && d && Array.isArray(d.news)) {
          setFeeds(processFeeds(d));
        }
      })
      .catch(() => {});
    return () => {
      active = false;
    };
  }, []);
  return feeds;
}