/**
 * Aktuelles – Typen & Feed-Loader.
 * Lädt zur Laufzeit `public/data/aktuelles_feeds.json`; Fallback ist der
 * gebündelte Build-Import. Wird vom monatlichen Workflow aktualisiert.
 */
import fallback from './aktuelles_feeds.json';

export interface Person { name: string; role: string; }

export interface NewsGalleryItem {
  url: string;
  title?: string;
  caption?: string;
}

export interface NewsItem {
  id: string;
  category: string;
  date: string;
  title: string;
  image: string;
  gallery?: NewsGalleryItem[];
  location?: string;
  shortText: string;
  highlights: string[];
  speech: string;
  persons: Person[];
  isAutoGenerated?: boolean;
  sourceEventId?: string;
  ticketLink?: string;
  ticketLabel?: string;
  eventDetails?: {
    dateFormatted?: string;
    time?: string;
    doorsOpen?: string;
    venue?: string;
    address?: string;
    runtime?: string;
    language?: string;
    subtitles?: string;
    note?: string;
  };
  customSectionTitle?: string;
  customSectionContent?: string;
}

export interface EventItem {
  id: string;
  title: string;
  titleTr?: string;
  date: string;
  location: string;
  locationTr?: string;
  category: string;
  categoryTr?: string;
  image: string;
  description: string;
  descriptionTr?: string;
  link: string;
}

export interface BlogItem {
  id: string;
  title: string;
  date: string;
  author: string;
  partnerName?: string;
  partnerUrl?: string;
  category: string;
  image: string;
  excerpt: string;
  link: string;
}

export interface AktuellesFeeds {
  generatedAt: string;
  lastUpdated: { news: string; events: string; blogs: string };
  news: NewsItem[];
  events: EventItem[];
  blogs: BlogItem[];
}

export interface CountdownInfo {
  status: 'past' | 'today' | 'tomorrow' | 'upcoming';
  days: number;
  label: string;
}

/**
 * Berechnet den "noch X Tage"-Countdown für ein Veranstaltungsdatum.
 */
export function getEventCountdown(isoDate?: string): CountdownInfo | null {
  if (!isoDate) return null;
  try {
    const target = new Date(isoDate);
    if (isNaN(target.getTime())) return null;

    const now = new Date();
    // Rechnen auf Tagesbasis (Mitternacht)
    const targetDay = new Date(target.getFullYear(), target.getMonth(), target.getDate()).getTime();
    const todayDay = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
    const diffDays = Math.round((targetDay - todayDay) / (1000 * 60 * 60 * 24));

    if (diffDays < 0) {
      return { status: 'past', days: diffDays, label: 'Vergangen' };
    }
    if (diffDays === 0) {
      return { status: 'today', days: 0, label: 'Heute!' };
    }
    if (diffDays === 1) {
      return { status: 'tomorrow', days: 1, label: 'Morgen!' };
    }
    return { status: 'upcoming', days: diffDays, label: `noch ${diffDays} Tage` };
  } catch {
    return null;
  }
}

/**
 * Gibt die Vereins-News nach Datum absteigend sortiert zurück.
 * Es werden keine automatischen Event-Rückblicke erzeugt (News bleiben reine Vereins-News).
 */
export function deriveAutoNewsFromEvents(events: EventItem[] = [], existingNews: NewsItem[] = []): NewsItem[] {
  const combined = [...existingNews];
  combined.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  return combined;
}

function normalizeAssetUrl(url?: string): string {
  if (!url) return '';
  if (url.startsWith('http://') || url.startsWith('https://') || url.startsWith('data:') || url.startsWith('//')) {
    return url;
  }
  const base = import.meta.env.BASE_URL || '/';
  const prefix = base.endsWith('/') ? base.slice(0, -1) : base;
  const path = url.startsWith('/') ? url : `/${url}`;
  return `${prefix}${path}`;
}

function processFeeds(raw: AktuellesFeeds): AktuellesFeeds {
  if (!raw) return raw;
  // News wird separat geführt und enthält nur echte Vereinsnachrichten (keine Duplikate aus Events)
  const rawNews = Array.isArray(raw.news) ? raw.news : [];
  const normalizedNews = rawNews.map((n) => ({
    ...n,
    image: normalizeAssetUrl(n.image),
    gallery: n.gallery?.map((g) => ({
      ...g,
      url: normalizeAssetUrl(g.url),
    })),
  }));
  return {
    ...raw,
    news: normalizedNews,
  };
}

export const AKTUELLES_FALLBACK = processFeeds(fallback as unknown as AktuellesFeeds);
export const AKTUELLES_URL = `${import.meta.env.BASE_URL}data/aktuelles_feeds.json`;

export function formatDate(iso?: string) {
  if (!iso) return '–';
  try {
    return new Date(iso).toLocaleDateString('de-DE', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
    });
  } catch {
    return '–';
  }
}

import { useEffect, useState } from 'react';

/** Lädt die Feeds zur Laufzeit, mit gebündeltem Fallback und Auto-News aus Events. */
export function useAktuelles(): AktuellesFeeds {
  const [feeds, setFeeds] = useState<AktuellesFeeds>(AKTUELLES_FALLBACK);
  useEffect(() => {
    let active = true;
    fetch(AKTUELLES_URL, { cache: 'no-cache' })
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((d: AktuellesFeeds) => {
        if (active && d && Array.isArray(d.news)) {
          setFeeds(processFeeds(d));
        }
      })
      .catch(() => {});
    return () => {
      active = false;
    };
  }, []);
  return feeds;
}